<Project Sdk="MSTest.Sdk/4.0.2">

  <PropertyGroup>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OSRTracker.Core\OSRTracker.Core.csproj" />
    <ProjectReference Include="..\OSRTracker\OSRTracker\OSRTracker.csproj" />
  </ItemGroup>

</Project>
