using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace WinUIEx.Generators;

[Generator]
public class RowWrapperGenerator : IIncrementalGenerator
{
   private const string AttributeName = "GenerateRowWrapperAttribute";
   private const string AttributeNamespace = "OSRTracker";

   private readonly string _attributeText = $@"// <auto-generated />
using System;

#pragma warning disable 1591

namespace {AttributeNamespace}
{{
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class {AttributeName} : Attribute
    {{
    }}
}}
";

   public void Initialize(IncrementalGeneratorInitializationContext context)
   {
#if DEBUG
      //System.Diagnostics.Debugger.Launch();
#endif
      context.RegisterPostInitializationOutput(ctx => ctx.AddSource($"{AttributeName}.g.cs", _attributeText));

      // Find class declarations that have attributes (fast filter)

      var cd = context.SyntaxProvider
         .ForAttributeWithMetadataName(
         fullyQualifiedMetadataName: $"{AttributeNamespace}.{AttributeName}",
         predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
         transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
         .Where(static m => m is not null)
         .Collect();

      context.RegisterSourceOutput(cd, Execute);

      //var classDeclarations = context.SyntaxProvider
      //   .CreateSyntaxProvider(
      //      predicate: static (s, _) => IsCandidate(s),
      //      transform: static (ctx, _) => GetSemanticTargetForGeneration((ClassDeclarationSyntax)ctx.Node, ctx.SemanticModel))
      //   .Where(static m => m is not null)!
      //   .Select((m, _) => m!)
      //   .Collect();

      //context.RegisterSourceOutput(classDeclarations, static (spc, classes) =>
      //{
      //   foreach (var model in classes)
      //   {
      //      try
      //      {
      //         var source = GenerateWrapperSource(model!);
      //         spc.AddSource($"{model!.Name}_RowWrapper.g.cs", SourceText.From(source, Encoding.UTF8));
      //      }
      //      catch (System.Exception ex)
      //      {
      //         // Don't crash the generator for a single type
      //         var hint = $"// Generator error: {ex.Message}\n";
      //         spc.AddSource($"{model!.Name}_RowWrapper_Error.g.cs", SourceText.From(hint, Encoding.UTF8));
      //      }
      //   }
      //});

   }

   static bool IsSyntaxTargetForGeneration(SyntaxNode node)
   {
      return node is ClassDeclarationSyntax classDeclarationSyntax
         && classDeclarationSyntax.Modifiers.Any(SyntaxKind.PartialKeyword);
   }

   static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorAttributeSyntaxContext context)
   {
      var symbol = context.TargetSymbol;

      if (symbol is not INamedTypeSymbol namedTypeSymbol)
      {
         return null;
      }

      var attributeData = namedTypeSymbol.GetAttributes().FirstOrDefault(ad =>
      string.Equals(ad.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), $"global::{AttributeNamespace}.{AttributeName}"));

      return attributeData is null ? null : namedTypeSymbol;
   }



   private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> symbols)
   {
      foreach (var namedTypeSymbol in symbols.Where(symbol => symbol is not null))
      {
         var classSource = ProcessClass(namedTypeSymbol!, context);

         if (classSource is null)
         {
            continue;
         }

         context.AddSource($"{namedTypeSymbol!.ContainingNamespace}_{namedTypeSymbol.Name}.g.cs", classSource);
      }
   }


   private static string? ProcessClass(INamedTypeSymbol classSymbol, SourceProductionContext context)
   {
      var attributeLocation = classSymbol.Locations.FirstOrDefault() ?? Location.None;

      if (!classSymbol.ContainingSymbol.Equals(classSymbol.ContainingNamespace, SymbolEqualityComparer.Default))
      {
         CreateDiagnosticError(GeneratorDiagnosticDescriptors.TopLevelError);
      }

      if (classSymbol.BaseType is null || classSymbol.BaseType.Name != "RowWrapperBase" || classSymbol.BaseType.ContainingNamespace.ToString() != "OSRTracker")
      {
         CreateDiagnosticError(GeneratorDiagnosticDescriptors.WrongBaseType);
         return null;
      }

      var typeArguments = classSymbol.BaseType.TypeArguments;

      if (typeArguments.Length != 1)
      {
         CreateDiagnosticError(GeneratorDiagnosticDescriptors.WrongBaseType);
         return null;
      }

      var typeArgument = typeArguments[0];

      {
         if (typeArgument.Name == nameof(Object))
         {
            CreateDiagnosticError(GeneratorDiagnosticDescriptors.ObjectIsRowWrapperBaseType);
            return null;
         }

         if (typeArgument.TypeKind == TypeKind.Interface)
         {
            CreateDiagnosticError(GeneratorDiagnosticDescriptors.UserDefinedConversionsToOrFromAnInterfaceAreNotAllowed);
            return null;
         }
      }

      return GenerateClassSource(classSymbol, classSymbol.BaseType.TypeParameters[0], typeArgument);

      void CreateDiagnosticError(DiagnosticDescriptor descriptor)
      {
         context.ReportDiagnostic(Diagnostic.Create(descriptor, attributeLocation, classSymbol.Name, DiagnosticSeverity.Error));
      }

   }

   private static string GenerateClassSource(INamedTypeSymbol classSymbol, ITypeParameterSymbol typeParameter, ITypeSymbol typeArgument)
   {
      var ns = classSymbol.ContainingNamespace.ToDisplayString();

      var modelName = classSymbol.Name;


      var sb = new StringBuilder();
      sb.AppendLine("// <auto-generated/>");
      sb.AppendLine("using System;");
      sb.AppendLine("using System.Collections.Generic;");
      sb.AppendLine("using OSRTracker;");
      sb.AppendLine();
      sb.AppendLine($"namespace {ns};");
      sb.AppendLine();
      sb.AppendLine($"public partial class {modelName}");
      sb.AppendLine("{");
      sb.AppendLine();

      List<string> propNames = [];

      // Generate properties
      foreach (var member in typeArgument.GetMembers().OfType<IPropertySymbol>())
      {
         if (member.IsStatic) continue;
         // Skip indexers
         if (member.Parameters.Length > 0) continue;

         var propName = member.Name;
         var propType = member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

         // Getter
         if (member.GetMethod != null)
         {
            sb.AppendLine($"    public {propType} {propName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        get => IsPlaceholder ? default({propType}) : Item.{propName};");

            // Setter
            if (member.SetMethod != null)
            {
               sb.AppendLine("        set");
               sb.AppendLine("        {");
               if (propType == "string")
               {
                  sb.AppendLine($"            if (IsPlaceholder && string.IsNullOrEmpty(value)) {{ return; }}");
               }
               else
               {
                  sb.AppendLine($"            if (IsPlaceholder && Equals(value, default({propType})))  {{ return; }}");
               }
               sb.AppendLine($"            var target = EnsureRealItem();");
               sb.AppendLine($"            target.{propName} = value;");
               sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
         }

         propNames.Add(propName);
      }

      sb.AppendLine();
      sb.AppendLine("    protected override void AllPropertiesChanged()");
      sb.AppendLine("    {");
      foreach (var propName in propNames)
      {
         sb.AppendLine($"        OnPropertyChanged(\"{propName}\");");
      }
      sb.AppendLine("    }");

      sb.AppendLine("}");

      return sb.ToString();
   }

   //private static bool IsCandidate(SyntaxNode node)
   //{
   //   return node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0;
   //}

   //private static INamedTypeSymbol? GetSemanticTargetForGeneration(ClassDeclarationSyntax classDecl, SemanticModel semanticModel)
   //{
   //   if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
   //   {
   //      return null;
   //   }

   //   foreach (var attr in symbol.GetAttributes())
   //   {
   //      var name = attr.AttributeClass?.ToDisplayString();
   //      if (name == "OSRTracker.ViewModels.GenerateRowWrapperAttribute" || name == "GenerateRowWrapperAttribute")
   //      {
   //         // Only support non-generic classes
   //         if (symbol.TypeParameters.Length == 0)
   //            return symbol;
   //      }
   //   }
   //   return null;
   //}

   //private static string GenerateWrapperSource(INamedTypeSymbol model)
   //{
   //   var ns = model.ContainingNamespace.ToDisplayString();

   //   var modelFullName = model.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
   //   var modelName = model.Name;
   //   var wrapperName = modelName + "RowWrapper";


   //   var sb = new StringBuilder();
   //   sb.AppendLine("// <auto-generated/>");
   //   sb.AppendLine("using System;");
   //   sb.AppendLine("using System.Collections.Generic;");
   //   sb.AppendLine("using OSRTracker.ViewModels;");
   //   sb.AppendLine();
   //   sb.AppendLine($"namespace {ns}");
   //   sb.AppendLine("{");
   //   sb.AppendLine($"    public sealed class {wrapperName} : RowWrapperBase<{modelFullName}>");
   //   sb.AppendLine("    {");
   //   sb.AppendLine($"        public {wrapperName}(Func<{modelFullName}> factory) : base(factory) {{ }}");
   //   sb.AppendLine($"        public {wrapperName}(Func<{modelFullName}> factory, {modelFullName} initial) : base(factory, initial) {{ }}");
   //   sb.AppendLine();

   //   // Generate properties
   //   foreach (var member in model.GetMembers().OfType<IPropertySymbol>())
   //   {
   //      if (member.IsStatic) continue;
   //      // Skip indexers
   //      if (member.Parameters.Length > 0) continue;

   //      var propName = member.Name;
   //      var propType = member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

   //      // Getter
   //      if (member.GetMethod != null)
   //      {
   //         sb.AppendLine($"        public {propType} {propName}");
   //         sb.AppendLine("        {");
   //         sb.AppendLine($"            get => IsPlaceholder ? default({propType}) : Item.{propName};");

   //         // Setter
   //         if (member.SetMethod != null)
   //         {
   //            sb.AppendLine("            set");
   //            sb.AppendLine("            {");
   //            sb.AppendLine($"                var target = EnsureRealItem();");
   //            sb.AppendLine($"                if (!EqualityComparer<{propType}>.Default.Equals(target.{propName}, value))");
   //            sb.AppendLine("                {");
   //            sb.AppendLine($"                    target.{propName} = value;");
   //            sb.AppendLine($"                    OnPropertyChanged(nameof({propName}));");
   //            sb.AppendLine("                }");
   //            sb.AppendLine("            }");
   //         }

   //         sb.AppendLine("        }");
   //         sb.AppendLine();
   //      }
   //   }

   //   sb.AppendLine("    }");
   //   sb.AppendLine("}");

   //   return sb.ToString();
   //}
}
