// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSRTracker.Data;

#nullable disable

namespace OSRTracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AttributeDefinitionClassDefinition", b =>
                {
                    b.Property<int>("ClassDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyAttributesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassDefinitionId", "KeyAttributesId");

                    b.HasIndex("KeyAttributesId");

                    b.ToTable("ClassKeyAttributes", (string)null);
                });

            modelBuilder.Entity("CharacterGeneralXPAward", b =>
                {
                    b.Property<int>("CharactersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneralXPAwardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharactersId", "GeneralXPAwardId");

                    b.HasIndex("GeneralXPAwardId");

                    b.ToTable("CharacterXPAward", (string)null);
                });

            modelBuilder.Entity("CharacterSession", b =>
                {
                    b.Property<int>("CharactersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharactersId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionCharacters", (string)null);
                });

            modelBuilder.Entity("OSRTracker.Models.AttributeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AttributeDefinitions", (string)null);
                });

            modelBuilder.Entity("OSRTracker.Models.CampaignSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CampaignSettings", (string)null);
                });

            modelBuilder.Entity("OSRTracker.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cha")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Con")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentXP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Int")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShareMultiplierTreasure")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShareMultiplierXP")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Str")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wis")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("OSRTracker.Models.ClassDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClassDefinitions", (string)null);
                });

            modelBuilder.Entity("OSRTracker.Models.CurrencyDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CountPerUnitWeight")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CurrencyDefinitions", (string)null);
                });

            modelBuilder.Entity("OSRTracker.Models.Delve", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionTrackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionTrackId");

                    b.ToTable("Delves", (string)null);
                });

            modelBuilder.Entity("OSRTracker.Models.GeneralXPAward", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DelveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DelveId");

                    b.HasIndex("SessionId");

                    b.ToTable("GeneralXPAwards", (string)null);
                });

            modelBuilder.Entity("OSRTracker.Models.MonsterEntry", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DelveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XPValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DelveId");

                    b.HasIndex("SessionId");

                    b.ToTable("MonsterEntries", (string)null);
                });

            modelBuilder.Entity("OSRTracker.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionTrackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionTrackId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("OSRTracker.Models.SessionDelve", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DelveId");

                    b.HasIndex("SessionId", "DelveId")
                        .IsUnique();

                    b.ToTable("SessionDelves", (string)null);
                });

            modelBuilder.Entity("OSRTracker.Models.SessionTrack", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SessionTracks", (string)null);
                });

            modelBuilder.Entity("OSRTracker.Models.SessionTrackCharacter", b =>
                {
                    b.Property<int>("SessionTrackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionTrackId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("SessionTracksCharacters", (string)null);
                });

            modelBuilder.Entity("OSRTracker.Models.TreasureEntry", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ApparentValue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DelveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantiy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "OSRTracker.Models.TreasureEntry.Location#LocationReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("CharacterId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("LocCharacterId");

                            b1.Property<string>("StoreDescription")
                                .HasColumnType("TEXT")
                                .HasColumnName("LocStore");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("LocType");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MagicItemDetails", "OSRTracker.Models.TreasureEntry.MagicItemDetails#MagicItemDetails", b1 =>
                        {
                            b1.Property<int>("IdentificationStatus")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("TrueValue")
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DelveId");

                    b.HasIndex("SessionId");

                    b.ToTable("TreasureEntries", (string)null);
                });

            modelBuilder.Entity("AttributeDefinitionClassDefinition", b =>
                {
                    b.HasOne("OSRTracker.Models.ClassDefinition", null)
                        .WithMany()
                        .HasForeignKey("ClassDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSRTracker.Models.AttributeDefinition", null)
                        .WithMany()
                        .HasForeignKey("KeyAttributesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterGeneralXPAward", b =>
                {
                    b.HasOne("OSRTracker.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSRTracker.Models.GeneralXPAward", null)
                        .WithMany()
                        .HasForeignKey("GeneralXPAwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSession", b =>
                {
                    b.HasOne("OSRTracker.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSRTracker.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OSRTracker.Models.Character", b =>
                {
                    b.HasOne("OSRTracker.Models.ClassDefinition", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Class");
                });

            modelBuilder.Entity("OSRTracker.Models.ClassDefinition", b =>
                {
                    b.OwnsMany("OSRTracker.Models.LevelXPRequirement", "LevelXP", b1 =>
                        {
                            b1.Property<int>("ClassDefinitionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("XP");

                            b1.HasKey("ClassDefinitionId", "__synthesizedOrdinal");

                            b1.ToTable("ClassDefinitions", (string)null);

                            b1
                                .ToJson("LevelXP")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("ClassDefinitionId");
                        });

                    b.Navigation("LevelXP");
                });

            modelBuilder.Entity("OSRTracker.Models.Delve", b =>
                {
                    b.HasOne("OSRTracker.Models.SessionTrack", "SessionTrack")
                        .WithMany("Delves")
                        .HasForeignKey("SessionTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionTrack");
                });

            modelBuilder.Entity("OSRTracker.Models.GeneralXPAward", b =>
                {
                    b.HasOne("OSRTracker.Models.Delve", "Delve")
                        .WithMany("GeneralXPAwards")
                        .HasForeignKey("DelveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OSRTracker.Models.Session", "Session")
                        .WithMany("GeneralXPAwards")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delve");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OSRTracker.Models.MonsterEntry", b =>
                {
                    b.HasOne("OSRTracker.Models.Delve", "Delve")
                        .WithMany("Monsters")
                        .HasForeignKey("DelveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OSRTracker.Models.Session", "Session")
                        .WithMany("Monsters")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delve");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OSRTracker.Models.Session", b =>
                {
                    b.HasOne("OSRTracker.Models.SessionTrack", "SessionTrack")
                        .WithMany("Sessions")
                        .HasForeignKey("SessionTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionTrack");
                });

            modelBuilder.Entity("OSRTracker.Models.SessionDelve", b =>
                {
                    b.HasOne("OSRTracker.Models.Delve", "Delve")
                        .WithMany("Sessions")
                        .HasForeignKey("DelveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSRTracker.Models.Session", "Session")
                        .WithMany("Delves")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delve");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OSRTracker.Models.SessionTrackCharacter", b =>
                {
                    b.HasOne("OSRTracker.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OSRTracker.Models.SessionTrack", "SessionTrack")
                        .WithMany("Characters")
                        .HasForeignKey("SessionTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("SessionTrack");
                });

            modelBuilder.Entity("OSRTracker.Models.TreasureEntry", b =>
                {
                    b.HasOne("OSRTracker.Models.Delve", "Delve")
                        .WithMany("Treasures")
                        .HasForeignKey("DelveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OSRTracker.Models.Session", "Session")
                        .WithMany("Treasures")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delve");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OSRTracker.Models.Delve", b =>
                {
                    b.Navigation("GeneralXPAwards");

                    b.Navigation("Monsters");

                    b.Navigation("Sessions");

                    b.Navigation("Treasures");
                });

            modelBuilder.Entity("OSRTracker.Models.Session", b =>
                {
                    b.Navigation("Delves");

                    b.Navigation("GeneralXPAwards");

                    b.Navigation("Monsters");

                    b.Navigation("Treasures");
                });

            modelBuilder.Entity("OSRTracker.Models.SessionTrack", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Delves");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
