// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using OSRTracker.CompiledModels;
using OSRTracker.Data;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
