// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace OSRTracker.Data.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("cf215d44-e7e8-4bd1-9cc8-6e7fff95053b"), entityTypeCount: 15)
        {
        }

        partial void Initialize()
        {
            var attributeDefinitionClassDefinition = AttributeDefinitionClassDefinitionEntityType.Create(this);
            var characterGeneralXPAward = CharacterGeneralXPAwardEntityType.Create(this);
            var characterSession = CharacterSessionEntityType.Create(this);
            var attributeDefinition = AttributeDefinitionEntityType.Create(this);
            var campaignSettings = CampaignSettingsEntityType.Create(this);
            var character = CharacterEntityType.Create(this);
            var classDefinition = ClassDefinitionEntityType.Create(this);
            var currencyDefinition = CurrencyDefinitionEntityType.Create(this);
            var delve = DelveEntityType.Create(this);
            var generalXPAward = GeneralXPAwardEntityType.Create(this);
            var levelXPRequirement = LevelXPRequirementEntityType.Create(this);
            var monsterEntry = MonsterEntryEntityType.Create(this);
            var session = SessionEntityType.Create(this);
            var sessionDelve = SessionDelveEntityType.Create(this);
            var treasureEntry = TreasureEntryEntityType.Create(this);

            AttributeDefinitionClassDefinitionEntityType.CreateForeignKey1(attributeDefinitionClassDefinition, classDefinition);
            AttributeDefinitionClassDefinitionEntityType.CreateForeignKey2(attributeDefinitionClassDefinition, attributeDefinition);
            CharacterGeneralXPAwardEntityType.CreateForeignKey1(characterGeneralXPAward, character);
            CharacterGeneralXPAwardEntityType.CreateForeignKey2(characterGeneralXPAward, generalXPAward);
            CharacterSessionEntityType.CreateForeignKey1(characterSession, character);
            CharacterSessionEntityType.CreateForeignKey2(characterSession, session);
            CharacterEntityType.CreateForeignKey1(character, classDefinition);
            GeneralXPAwardEntityType.CreateForeignKey1(generalXPAward, sessionDelve);
            LevelXPRequirementEntityType.CreateForeignKey1(levelXPRequirement, classDefinition);
            MonsterEntryEntityType.CreateForeignKey1(monsterEntry, sessionDelve);
            SessionDelveEntityType.CreateForeignKey1(sessionDelve, delve);
            SessionDelveEntityType.CreateForeignKey2(sessionDelve, session);
            TreasureEntryEntityType.CreateForeignKey1(treasureEntry, sessionDelve);

            AttributeDefinitionEntityType.CreateSkipNavigation1(attributeDefinition, classDefinition, attributeDefinitionClassDefinition);
            CharacterEntityType.CreateSkipNavigation1(character, generalXPAward, characterGeneralXPAward);
            CharacterEntityType.CreateSkipNavigation2(character, session, characterSession);
            ClassDefinitionEntityType.CreateSkipNavigation1(classDefinition, attributeDefinition, attributeDefinitionClassDefinition);
            GeneralXPAwardEntityType.CreateSkipNavigation1(generalXPAward, character, characterGeneralXPAward);
            SessionEntityType.CreateSkipNavigation1(session, character, characterSession);

            AttributeDefinitionClassDefinitionEntityType.CreateAnnotations(attributeDefinitionClassDefinition);
            CharacterGeneralXPAwardEntityType.CreateAnnotations(characterGeneralXPAward);
            CharacterSessionEntityType.CreateAnnotations(characterSession);
            AttributeDefinitionEntityType.CreateAnnotations(attributeDefinition);
            CampaignSettingsEntityType.CreateAnnotations(campaignSettings);
            CharacterEntityType.CreateAnnotations(character);
            ClassDefinitionEntityType.CreateAnnotations(classDefinition);
            CurrencyDefinitionEntityType.CreateAnnotations(currencyDefinition);
            DelveEntityType.CreateAnnotations(delve);
            GeneralXPAwardEntityType.CreateAnnotations(generalXPAward);
            LevelXPRequirementEntityType.CreateAnnotations(levelXPRequirement);
            MonsterEntryEntityType.CreateAnnotations(monsterEntry);
            SessionEntityType.CreateAnnotations(session);
            SessionDelveEntityType.CreateAnnotations(sessionDelve);
            TreasureEntryEntityType.CreateAnnotations(treasureEntry);

            AddAnnotation("ProductVersion", "10.0.8");
        }
    }
}
