// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace OSRTracker.Data.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("25b5a0e2-d3cb-4294-9b93-6e15d0c695a8"), entityTypeCount: 18)
        {
        }

        partial void Initialize()
        {
            var attributeDefinitionClassDefinition = AttributeDefinitionClassDefinitionEntityType.Create(this);
            var characterGeneralXPAward = CharacterGeneralXPAwardEntityType.Create(this);
            var attributeDefinition = AttributeDefinitionEntityType.Create(this);
            var campaignSettings = CampaignSettingsEntityType.Create(this);
            var character = CharacterEntityType.Create(this);
            var classDefinition = ClassDefinitionEntityType.Create(this);
            var currencyDefinition = CurrencyDefinitionEntityType.Create(this);
            var delve = DelveEntityType.Create(this);
            var delveCharacter = DelveCharacterEntityType.Create(this);
            var generalXPAward = GeneralXPAwardEntityType.Create(this);
            var levelXPRequirement = LevelXPRequirementEntityType.Create(this);
            var monsterEntry = MonsterEntryEntityType.Create(this);
            var session = SessionEntityType.Create(this);
            var sessionCharacter = SessionCharacterEntityType.Create(this);
            var sessionDelve = SessionDelveEntityType.Create(this);
            var sessionTrack = SessionTrackEntityType.Create(this);
            var sessionTrackCharacter = SessionTrackCharacterEntityType.Create(this);
            var treasureEntry = TreasureEntryEntityType.Create(this);

            AttributeDefinitionClassDefinitionEntityType.CreateForeignKey1(attributeDefinitionClassDefinition, classDefinition);
            AttributeDefinitionClassDefinitionEntityType.CreateForeignKey2(attributeDefinitionClassDefinition, attributeDefinition);
            CharacterGeneralXPAwardEntityType.CreateForeignKey1(characterGeneralXPAward, character);
            CharacterGeneralXPAwardEntityType.CreateForeignKey2(characterGeneralXPAward, generalXPAward);
            CharacterEntityType.CreateForeignKey1(character, classDefinition);
            DelveEntityType.CreateForeignKey1(delve, sessionTrack);
            DelveCharacterEntityType.CreateForeignKey1(delveCharacter, character);
            DelveCharacterEntityType.CreateForeignKey2(delveCharacter, delve);
            GeneralXPAwardEntityType.CreateForeignKey1(generalXPAward, delve);
            GeneralXPAwardEntityType.CreateForeignKey2(generalXPAward, session);
            LevelXPRequirementEntityType.CreateForeignKey1(levelXPRequirement, classDefinition);
            MonsterEntryEntityType.CreateForeignKey1(monsterEntry, delve);
            MonsterEntryEntityType.CreateForeignKey2(monsterEntry, session);
            SessionEntityType.CreateForeignKey1(session, sessionTrack);
            SessionCharacterEntityType.CreateForeignKey1(sessionCharacter, character);
            SessionCharacterEntityType.CreateForeignKey2(sessionCharacter, session);
            SessionDelveEntityType.CreateForeignKey1(sessionDelve, delve);
            SessionDelveEntityType.CreateForeignKey2(sessionDelve, session);
            SessionTrackCharacterEntityType.CreateForeignKey1(sessionTrackCharacter, character);
            SessionTrackCharacterEntityType.CreateForeignKey2(sessionTrackCharacter, sessionTrack);
            TreasureEntryEntityType.CreateForeignKey1(treasureEntry, delve);
            TreasureEntryEntityType.CreateForeignKey2(treasureEntry, session);

            AttributeDefinitionEntityType.CreateSkipNavigation1(attributeDefinition, classDefinition, attributeDefinitionClassDefinition);
            CharacterEntityType.CreateSkipNavigation1(character, generalXPAward, characterGeneralXPAward);
            CharacterEntityType.CreateSkipNavigation2(character, sessionTrack, sessionTrackCharacter);
            ClassDefinitionEntityType.CreateSkipNavigation1(classDefinition, attributeDefinition, attributeDefinitionClassDefinition);
            GeneralXPAwardEntityType.CreateSkipNavigation1(generalXPAward, character, characterGeneralXPAward);
            SessionTrackEntityType.CreateSkipNavigation1(sessionTrack, character, sessionTrackCharacter);

            AttributeDefinitionClassDefinitionEntityType.CreateAnnotations(attributeDefinitionClassDefinition);
            CharacterGeneralXPAwardEntityType.CreateAnnotations(characterGeneralXPAward);
            AttributeDefinitionEntityType.CreateAnnotations(attributeDefinition);
            CampaignSettingsEntityType.CreateAnnotations(campaignSettings);
            CharacterEntityType.CreateAnnotations(character);
            ClassDefinitionEntityType.CreateAnnotations(classDefinition);
            CurrencyDefinitionEntityType.CreateAnnotations(currencyDefinition);
            DelveEntityType.CreateAnnotations(delve);
            DelveCharacterEntityType.CreateAnnotations(delveCharacter);
            GeneralXPAwardEntityType.CreateAnnotations(generalXPAward);
            LevelXPRequirementEntityType.CreateAnnotations(levelXPRequirement);
            MonsterEntryEntityType.CreateAnnotations(monsterEntry);
            SessionEntityType.CreateAnnotations(session);
            SessionCharacterEntityType.CreateAnnotations(sessionCharacter);
            SessionDelveEntityType.CreateAnnotations(sessionDelve);
            SessionTrackEntityType.CreateAnnotations(sessionTrack);
            SessionTrackCharacterEntityType.CreateAnnotations(sessionTrackCharacter);
            TreasureEntryEntityType.CreateAnnotations(treasureEntry);

            AddAnnotation("ProductVersion", "10.0.9");
        }
    }
}
