// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSRTracker.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace OSRTracker.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TreasureEntryEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "OSRTracker.Models.TreasureEntry",
                typeof(TreasureEntry),
                baseEntityType,
                propertyCount: 10,
                complexPropertyCount: 2,
                navigationCount: 2,
                foreignKeyCount: 2,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(TreasureEntryId),
                propertyInfo: typeof(TreasureEntry).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw);
            id.SetValueConverter(new ValueConverter<TreasureEntryId, int>(
                int (TreasureEntryId x) => x.Value,
                TreasureEntryId (int id) => new TreasureEntryId(id)));
            id.SetSentinelFromProviderValue(0);
            id.AddAnnotation("Relational:ColumnType", "INTEGER");
            id.AddAnnotation("Sqlite:ValueGenerationStrategy", SqliteValueGenerationStrategy.Autoincrement);

            var applicationStatus = runtimeEntityType.AddProperty(
                "ApplicationStatus",
                typeof(TreasureEntryApplicationStatus),
                propertyInfo: typeof(TreasureEntry).GetProperty("ApplicationStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<ApplicationStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            applicationStatus.SetSentinelFromProviderValue(0);

            var delveId = runtimeEntityType.AddProperty(
                "DelveId",
                typeof(DelveId?),
                propertyInfo: typeof(TreasureEntry).GetProperty("DelveId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<DelveId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(TreasureEntry).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var notes = runtimeEntityType.AddProperty(
                "Notes",
                typeof(string),
                propertyInfo: typeof(TreasureEntry).GetProperty("Notes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<Notes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var quantiy = runtimeEntityType.AddProperty(
                "Quantiy",
                typeof(int),
                propertyInfo: typeof(TreasureEntry).GetProperty("Quantiy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<Quantiy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var saleStatus = runtimeEntityType.AddProperty(
                "SaleStatus",
                typeof(TreasureSale),
                propertyInfo: typeof(TreasureEntry).GetProperty("SaleStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<SaleStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            saleStatus.SetSentinelFromProviderValue(0);

            var sessionId = runtimeEntityType.AddProperty(
                "SessionId",
                typeof(SessionId),
                propertyInfo: typeof(TreasureEntry).GetProperty("SessionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<SessionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            sessionId.SetSentinelFromProviderValue(0);

            var value = runtimeEntityType.AddProperty(
                "Value",
                typeof(decimal),
                propertyInfo: typeof(TreasureEntry).GetProperty("Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);

            var weight = runtimeEntityType.AddProperty(
                "Weight",
                typeof(decimal),
                propertyInfo: typeof(TreasureEntry).GetProperty("Weight", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<Weight>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);

            LocationComplexProperty.Create(runtimeEntityType);
            MagicItemDetailsComplexProperty.Create(runtimeEntityType);
            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { delveId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { sessionId });

            return runtimeEntityType;
        }

        public static class LocationComplexProperty
        {
            public static RuntimeComplexProperty Create(RuntimeEntityType declaringType)
            {
                var complexProperty = declaringType.AddComplexProperty("Location",
                    typeof(LocationReference),
                    "OSRTracker.Models.TreasureEntry.Location#LocationReference",
                    typeof(LocationReference),
                    propertyInfo: typeof(TreasureEntry).GetProperty("Location", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(TreasureEntry).GetField("<Location>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    propertyCount: 3);

                var complexType = complexProperty.ComplexType;
                var characterId = complexType.AddProperty(
                    "CharacterId",
                    typeof(CharacterId?),
                    propertyInfo: typeof(LocationReference).GetProperty("CharacterId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(LocationReference).GetField("<CharacterId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    nullable: true);
                characterId.SetValueConverter(new ValueConverter<CharacterId?, int?>(
                    int? (CharacterId? x) => (x.HasValue ? ((int? )(x.Value.Value)) : null),
                    CharacterId? (int? id) => (id.HasValue ? ((CharacterId? )(new CharacterId(id.Value))) : null)));
                characterId.AddAnnotation("Relational:ColumnName", "LocCharacterId");

                var storeDescription = complexType.AddProperty(
                    "StoreDescription",
                    typeof(string),
                    propertyInfo: typeof(LocationReference).GetProperty("StoreDescription", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(LocationReference).GetField("<StoreDescription>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    nullable: true);
                storeDescription.AddAnnotation("Relational:ColumnName", "LocStore");

                var type = complexType.AddProperty(
                    "Type",
                    typeof(LocationType),
                    propertyInfo: typeof(LocationReference).GetProperty("Type", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(LocationReference).GetField("<Type>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
                type.SetSentinelFromProviderValue(0);
                type.AddAnnotation("Relational:ColumnName", "LocType");

                complexType.AddAnnotation("Relational:FunctionName", null);
                complexType.AddAnnotation("Relational:Schema", null);
                complexType.AddAnnotation("Relational:SqlQuery", null);
                complexType.AddAnnotation("Relational:TableName", "TreasureEntries");
                complexType.AddAnnotation("Relational:ViewName", null);
                complexType.AddAnnotation("Relational:ViewSchema", null);
                return complexProperty;
            }
        }

        public static class MagicItemDetailsComplexProperty
        {
            public static RuntimeComplexProperty Create(RuntimeEntityType declaringType)
            {
                var complexProperty = declaringType.AddComplexProperty("MagicItemDetails",
                    typeof(MagicItemDetails),
                    "OSRTracker.Models.TreasureEntry.MagicItemDetails#MagicItemDetails",
                    typeof(MagicItemDetails),
                    propertyInfo: typeof(TreasureEntry).GetProperty("MagicItemDetails", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(TreasureEntry).GetField("<MagicItemDetails>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    nullable: true,
                    propertyCount: 2);

                var complexType = complexProperty.ComplexType;
                var apparentValue = complexType.AddProperty(
                    "ApparentValue",
                    typeof(decimal),
                    propertyInfo: typeof(MagicItemDetails).GetProperty("ApparentValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(MagicItemDetails).GetField("<ApparentValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    sentinel: 0m);

                var identificationStatus = complexType.AddProperty(
                    "IdentificationStatus",
                    typeof(IdentificationStatus),
                    propertyInfo: typeof(MagicItemDetails).GetProperty("IdentificationStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(MagicItemDetails).GetField("<IdentificationStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
                identificationStatus.SetSentinelFromProviderValue(0);

                complexType.AddAnnotation("Relational:FunctionName", null);
                complexType.AddAnnotation("Relational:Schema", null);
                complexType.AddAnnotation("Relational:SqlQuery", null);
                complexType.AddAnnotation("Relational:TableName", "TreasureEntries");
                complexType.AddAnnotation("Relational:ViewName", null);
                complexType.AddAnnotation("Relational:ViewSchema", null);
                return complexProperty;
            }
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("DelveId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.SetNull);

            var delve = declaringEntityType.AddNavigation("Delve",
                runtimeForeignKey,
                onDependent: true,
                typeof(Delve),
                propertyInfo: typeof(TreasureEntry).GetProperty("Delve", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<Delve>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var treasures = principalEntityType.AddNavigation("Treasures",
                runtimeForeignKey,
                onDependent: false,
                typeof(List<TreasureEntry>),
                propertyInfo: typeof(Delve).GetProperty("Treasures", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Delve).GetField("<Treasures>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SessionId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var session = declaringEntityType.AddNavigation("Session",
                runtimeForeignKey,
                onDependent: true,
                typeof(Session),
                propertyInfo: typeof(TreasureEntry).GetProperty("Session", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<Session>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var treasures = principalEntityType.AddNavigation("Treasures",
                runtimeForeignKey,
                onDependent: false,
                typeof(List<TreasureEntry>),
                propertyInfo: typeof(Session).GetProperty("Treasures", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Session).GetField("<Treasures>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "TreasureEntries");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
