// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSRTracker.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace OSRTracker.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TreasureEntryEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "OSRTracker.Models.TreasureEntry",
                typeof(TreasureEntry),
                baseEntityType,
                propertyCount: 7,
                complexPropertyCount: 2,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(TreasureEntryId),
                propertyInfo: typeof(TreasureEntry).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            id.SetValueConverter(new ValueConverter<TreasureEntryId, int>(
                int (TreasureEntryId x) => x.Id,
                TreasureEntryId (int id) => new TreasureEntryId(id)));
            id.SetSentinelFromProviderValue(0);

            var apparentValue = runtimeEntityType.AddProperty(
                "ApparentValue",
                typeof(decimal),
                propertyInfo: typeof(TreasureEntry).GetProperty("ApparentValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<ApparentValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(TreasureEntry).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var notes = runtimeEntityType.AddProperty(
                "Notes",
                typeof(string),
                propertyInfo: typeof(TreasureEntry).GetProperty("Notes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<Notes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var quantiy = runtimeEntityType.AddProperty(
                "Quantiy",
                typeof(int),
                propertyInfo: typeof(TreasureEntry).GetProperty("Quantiy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<Quantiy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var sessionDelveId = runtimeEntityType.AddProperty(
                "SessionDelveId",
                typeof(SessionDelveId),
                propertyInfo: typeof(TreasureEntry).GetProperty("SessionDelveId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<SessionDelveId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            sessionDelveId.SetSentinelFromProviderValue(0);

            var weight = runtimeEntityType.AddProperty(
                "Weight",
                typeof(decimal),
                propertyInfo: typeof(TreasureEntry).GetProperty("Weight", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<Weight>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);

            LocationComplexProperty.Create(runtimeEntityType);
            MagicItemDetailsComplexProperty.Create(runtimeEntityType);
            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { sessionDelveId });

            return runtimeEntityType;
        }

        public static class LocationComplexProperty
        {
            public static RuntimeComplexProperty Create(RuntimeEntityType declaringType)
            {
                var complexProperty = declaringType.AddComplexProperty("Location",
                    typeof(LocationReference),
                    "OSRTracker.Models.TreasureEntry.Location#LocationReference",
                    typeof(LocationReference),
                    propertyInfo: typeof(TreasureEntry).GetProperty("Location", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(TreasureEntry).GetField("<Location>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    propertyCount: 3);

                var complexType = complexProperty.ComplexType;
                var characterId = complexType.AddProperty(
                    "CharacterId",
                    typeof(int?),
                    propertyInfo: typeof(LocationReference).GetProperty("CharacterId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(LocationReference).GetField("<CharacterId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    nullable: true);
                characterId.AddAnnotation("Relational:ColumnName", "LocCharacterId");

                var storeDescription = complexType.AddProperty(
                    "StoreDescription",
                    typeof(string),
                    propertyInfo: typeof(LocationReference).GetProperty("StoreDescription", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(LocationReference).GetField("<StoreDescription>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    nullable: true);
                storeDescription.AddAnnotation("Relational:ColumnName", "LocStore");

                var type = complexType.AddProperty(
                    "Type",
                    typeof(LocationType),
                    propertyInfo: typeof(LocationReference).GetProperty("Type", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(LocationReference).GetField("<Type>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
                type.SetSentinelFromProviderValue(0);
                type.AddAnnotation("Relational:ColumnName", "LocType");

                complexType.AddAnnotation("Relational:FunctionName", null);
                complexType.AddAnnotation("Relational:Schema", null);
                complexType.AddAnnotation("Relational:SqlQuery", null);
                complexType.AddAnnotation("Relational:TableName", "TreasureEntries");
                complexType.AddAnnotation("Relational:ViewName", null);
                complexType.AddAnnotation("Relational:ViewSchema", null);
                return complexProperty;
            }
        }

        public static class MagicItemDetailsComplexProperty
        {
            public static RuntimeComplexProperty Create(RuntimeEntityType declaringType)
            {
                var complexProperty = declaringType.AddComplexProperty("MagicItemDetails",
                    typeof(MagicItemDetails),
                    "OSRTracker.Models.TreasureEntry.MagicItemDetails#MagicItemDetails",
                    typeof(MagicItemDetails),
                    propertyInfo: typeof(TreasureEntry).GetProperty("MagicItemDetails", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(TreasureEntry).GetField("<MagicItemDetails>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    nullable: true,
                    propertyCount: 2);

                var complexType = complexProperty.ComplexType;
                var identificationStatus = complexType.AddProperty(
                    "IdentificationStatus",
                    typeof(IdentificationStatus),
                    propertyInfo: typeof(MagicItemDetails).GetProperty("IdentificationStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(MagicItemDetails).GetField("<IdentificationStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
                identificationStatus.SetSentinelFromProviderValue(0);

                var trueValue = complexType.AddProperty(
                    "TrueValue",
                    typeof(decimal?),
                    propertyInfo: typeof(MagicItemDetails).GetProperty("TrueValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(MagicItemDetails).GetField("<TrueValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    nullable: true);

                complexType.AddAnnotation("Relational:FunctionName", null);
                complexType.AddAnnotation("Relational:Schema", null);
                complexType.AddAnnotation("Relational:SqlQuery", null);
                complexType.AddAnnotation("Relational:TableName", "TreasureEntries");
                complexType.AddAnnotation("Relational:ViewName", null);
                complexType.AddAnnotation("Relational:ViewSchema", null);
                return complexProperty;
            }
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SessionDelveId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var sessionDelve = declaringEntityType.AddNavigation("SessionDelve",
                runtimeForeignKey,
                onDependent: true,
                typeof(SessionDelve),
                propertyInfo: typeof(TreasureEntry).GetProperty("SessionDelve", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TreasureEntry).GetField("<SessionDelve>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var treasures = principalEntityType.AddNavigation("Treasures",
                runtimeForeignKey,
                onDependent: false,
                typeof(List<TreasureEntry>),
                propertyInfo: typeof(SessionDelve).GetProperty("Treasures", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SessionDelve).GetField("<Treasures>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "TreasureEntries");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
